### ISSUE TITLE
Make PeopleMover accessible to people not on VPN

### ISSUE THREAD

**Issue by jshaddac** [FordLabs/PeopleMover#167]
- [ ] #163  TimeOut should take you to Login Page
- [ ] #34 Invite Users Without Logins to My Space
- [ ] #158 Fix Password reset to have confirmation message 
- [ ] #115 Add note about verification email taking approximately 10-15 mins to recieve
- [ ] #160 Fix link to go back to login on the Reset Password Modal
- [ ] #120 Add ability to change password from account dropdown
- [ ] #127 Make "Good" Password Criteria Required
- [ ] #83 Make "Good" Password Criteria Visible for Sign Up
- [ ] #46 Email Notification for those Invited to Space

User Feedback:
* Half of people who the Compliance Office would want to use PeopleMover do not have VPN access. 
* Other users have stated they avoid VPN because of other issues it causes.

**Comment by LowBudgetMan** [comment]
This would be good after we add ADFS
