### ISSUE TITLE
EPIC: Create Calendar Dropdown

### ISSUE THREAD

**Issue by tslo11** [FordLabs/PeopleMover#18]
# Feature Request

- [x] #65 Calendar Date Dropdown - Part 0: Replace board tabs with calendar view
- [x] #1 Calendar Date Dropdown - Part 1: Show most recent adjusted day for day with no changes
- [x] #2 Calendar Date Dropdown - Part 2: Calendar dropdown should show days with changes
- [ ] #12 Calendar Date Dropdown Transition: Do the Transition work from Board to Calendar
- [x] #6 Calendar Date Dropdown - Part 4: Reassigned drawer should show diff between days
- [x] #8 Calendar Date Dropdown - Part 5: Products Added Should Appear on Future Calendar Dates
- [ ] #10 Calendar Date Dropdown - Part 6: Making a new assignment for a person can affect their future assignments
